GET http://localhost:5086/games

###

GET http://localhost:5086/games/1

###

POST http://localhost:5086/games
Content-Type: application/json

{
    "name": "Test Game",
    "genreId": 1,
    "price": "29.99",
    "releaseDate": "2027-01-09"
}

###
PUT http://localhost:5086/games/1
Content-Type: application/json

 {
    "name": "Call of Duty Black Ops 2",
    "genreId": 1,
    "price": 49.99,
    "releaseDate": "2012-06-18"
  }


###
DELETE http://localhost:5086/games/7

###

GET http://localhost:5086/genres


